### ISSUE TITLE
Comments at the top of main.go cause crash when running server

### ISSUE THREAD

**Issue by msmolkin** [zakkor/lluminous#2]
# Issue with comments

I tried building lluminous on my machine. The client built easily. The server had an issue:

`main.go:24:12: pattern dist-client/*: no matching files found`

The fix was simple and straightforward. Just remove the comments at the top of the file.
Delete lines 24 and 25.

Great project!

---

### Additional info that might help someone trying to set up the server:

Requirements:
```sh
git clone https://github.com/zakkor/lluminous/
npm i
brew install go  # sudo apt install go
```

---

If editing in and launching from VS Code, you can create a launch.json file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "1. Start client",
            "type": "node-terminal",
            "request": "launch",
            "command": "npm i && npm run dev",
            "cwd": "${workspaceFolder}",
            "skipFiles": [
                "<node_internals>/**"
            ]
        },
        {
            "name": "2. Start server",
            "type": "node-terminal",
            "request": "launch",
            "command": "cd server && go build && PASSWORD=\"password\" ./server -sandbox /tmp/lluminous-sandbox",
            "cwd": "${workspaceFolder}",
            "skipFiles": [
                "<node_internals>/**"
            ]
        },
    ]
}
```

If not using VS Code, then just run the commands manually from your terminal:
```sh
# cd into lluminous directory
npm i && npm run dev # start client in one terminal window/container
cd server && go build && PASSWORD=\"password\" ./server -sandbox /tmp/lluminous-sandbox # start server in another
```

**Comment by zakkor** [comment]
Sorry about that, I added some easier installation methods where both the client+server are prepackaged into a single binary, but it broke the build in cases where your `dist-client` directory is empty. I've fixed that now, and added a note in the README: https://github.com/zakkor/lluminous?tab=readme-ov-file#single-binary

(If you already got them running separately as you've already done, there's no need to use that method).

It should build correctly now if you do a `git pull`.
