### ISSUE TITLE
Windows version does not work

### ISSUE THREAD

**Issue by zdenop** [zakkor/lluminous#4]
I tried to run app on windows and it close with error:
>lluminous-windows-amd64.exe
2024/06/05 09:39:27 open /Users/ed/src/lluminous/server/tools/tools.go: The system cannot find the path specified.

**Comment by zakkor** [comment]
Hello, yes, unfortunately there's an issue with the current distribution method through the Releases page. It requires a rewrite of the tool system, which someone has already done, and it'll be integrated soon.

In the mean time you can try running it using the instructions in the readme, but that will require you to install node and Go. 

It will be properly fixed soon, sorry!

**Comment by zakkor** [comment]
@zdenop should be fixed now! Re-download from the releases page and it should work.

**Comment by zdenop** [comment]
thanks it works.
